server:
  port: 9037

spring:
  rabbitmq:
    host: 30.129.3.25
    port: 5672
    username: admin
    password: Bp12345
    virtual-host: root
  datasource:
    url: jdbc:mysql://30.129.3.20/wisdom_prison_sys?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
    username: root
    password: Bp12345
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    default-property-inclusion: NON_NULL
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      fail-on-empty-beans: false
      fail-on-self-references: false
  application:
    name: sixsys
security:
  oauth2:
    resource:
      user-info-uri: http://30.129.3.25/oauth/user-me
      prefer-token-info: false
eureka:
  client:
    service-url:
      defaultZone: http://30.129.3.25:8010/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}
    #    ${spring.application.name}:${random.value}
    prefer-ip-address: true
mybatis-plus:
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
#  configuration:
#    map-underscore-to-camel-case: true]
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 15000
ribbon:
  ReadTimeout: 6000
  ConnectTimeout: 6000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
  OkToRetryOnAllOperations: false
logging:
  level:
    com.bp.sixsys.mapper: debug
  file: c:/log/sixsys.log
tx-lcn:
  client:
    manager-address: 30.129.3.10:8070
  ribbon:
    loadbalancer:
      dtx:
        enabled: false
    ReadTimeout: 6000
    ConnectTimeout: 6000
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 0
    OkToRetryOnAllOperations: false
