server:
  port: 0
  tomcat:
    max-http-post-size: 10000000
    max-http-header-size: 10000000
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.7:8010/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
    instance-id: file
#    ${spring.application.name}:${random.value}
spring:
  application:
    name: file
  session:
    store-type: redis
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: 123456
    virtual-host: root
    listener:
      simple:
        concurrency: 20
        max-concurrency: 50
  datasource:
    url: jdbc:mysql://192.168.1.7/smart_prison_file?characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20z
    maxPoolPreparedStatementPerConnectionSize: 20
  servlet:
    multipart:
      file-size-threshold: 10Mb
      max-file-size: 1000Mb
      max-request-size: 1000Mb
      location: c:/tmp/fileUpload
mybatis-plus:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
security:
  oauth2:
    resource:
      user-info-uri: http://192.168.1.7:9527/oauth/user-me
      prefer-token-info: false
file:
  local:
    path: c:/localFile
    prefix: /statics
    urlPrefix: http://192.168.1.7:8080/api-f${file.local.prefix}
  aliyun:
    endpoint: oss-cn-beijing.aliyuncs.com
    accessKeyId: LTAIMHvhlYwzkMIn
    accessKeySecret: AGHCVjaKhXwBuaDRb8XAv6mZeRkgTx
    bucketName: 20190307
    domain: https://20190307.oss-cn-beijing.aliyuncs.com
